# Generated by Django 3.2.13 on 2022-05-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscheduler', '0002_auto_20220517_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_number', models.CharField(default='', max_length=64, verbose_name='학번')),
                ('lecture_number_list', models.CharField(blank=True, default='', max_length=2048, null=True, verbose_name='학수번호')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
