# Generated by Django 3.2.13 on 2022-05-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartscheduler', '0004_alter_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
